import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import {
  ClerkProvider,
} from "@clerk/nextjs";
import Provider from "./provider";
import {Toaster} from '@/components/ui/sonner'
import "./globals.css";

const montserrat = Montserrat({
  weight: ["200", "300", "400", "500", "600", "700", "800", "900"],
  subsets: ["latin"], // Add Latin subset for full language support
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider afterSignInUrl="/dashboard" afterSignUpUrl="/dashboard">
      <html lang="en">
        <body className={`${montserrat.className} antialiased`}>
          <Provider>{children}</Provider>
          <Toaster />
        </body>
      </html>
    </ClerkProvider>
  );
}
